### ISSUE TITLE
an understantable setup-guide is missing

### ISSUE THREAD

**Issue by thengineer** [GavriYashar/Matlab-Editor-Plugin#136]
I'd love to use this plugin, but apparently I am incapable of installing it.
What I've done so far:
- downloaded the two .jar's and placed them in `C:\Users\Jakob\Documents\MATLAB\MEP`
- executed the `MEP_1.30.jar`. 
And here is where the confusion starts: 
I am not sure if the location of _javaclasspath.txt_ is freely configurable or if it should be in `prefdir` as sugessted on matlab-fileexchange, or the path that's pre-seleted. I've tried both and neither seems to work.
Then I am also not sure what to choose as _Installation directory_. Is that the location where Matlab is installed?

Can anyone please enlighten me? I'd also volunteer to improve the wiki on that part.

**Comment by thengineer** [comment]
I addition, when calling the  `at.mep.Start.start(...)` I get the following error:

	>> at.mep.Start.start('C:\Users\Jakob\Documents\MATLAB\MEP\CustomProps.properties', 'C:\Users\Jakob\Documents\MATLAB\MEP\DefaultProps.properties')
	Warning: A Java exception occurred trying to load the at/mep/Start class:
	Java exception occurred:
	java.lang.UnsupportedClassVersionError: at/mep/Start : Unsupported major.minor version 52.0
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(Unknown Source)
		at java.security.SecureClassLoader.defineClass(Unknown Source)
		at java.net.URLClassLoader.defineClass(Unknown Source)
		at java.net.URLClassLoader.access$100(Unknown Source)
		at java.net.URLClassLoader$1.run(Unknown Source)
		at java.net.URLClassLoader$1.run(Unknown Source)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Unknown Source)
		at com.mathworks.jmi.OpaqueJavaInterface.findClass(OpaqueJavaInterface.java:181)
	Undefined variable "at" or class "at.mep.Start.start". 

When running the same command a second time I get a different output:

	>> at.mep.Start.start('C:\Users\Jakob\Documents\MATLAB\MEP\CustomProps.properties', 'C:\Users\Jakob\Documents\MATLAB\MEP\DefaultProps.properties')
	Undefined variable "at" or class "at.mep.Start.start".

**Comment by GavriYashar** [comment]
Have you tried to install it manually?

>[...] the location of javaclasspath.txt is freely configurable or [...]

As mentioned in the [Setup guide ](https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Setup#installer) you should create the javaclasspath.txt in prefdir. Alternatively you can create it in the startup folder as mentioned [here](https://de.mathworks.com/help/matlab/matlab_external/static-path.html#bvnynym).

**Comment by Nigsia** [comment]
2017a is using Java 1.7.0_60-b19. Would it be possible for you to compile it in that version?

**Comment by GavriYashar** [comment]
I use a lot of lambda expressions. So for Java 7 I would have to rewrite some code, this will take some time.

**Comment by Nigsia** [comment]
Line up and line down have the following error (this is the main reason I wanted 1.30 instead of 1.25 :P)

`Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.lang.String.join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String;
	at at.mep.editor.EditorWrapper.moveCurrentLinesUp(EditorWrapper.java:656)
	at at.mep.editor.EMEPAction.doMoveLineUp(EMEPAction.java:279)
	at at.mep.editor.EMEPAction.access$1100(EMEPAction.java:23)
	at at.mep.editor.EMEPAction$15.actionPerformed(EMEPAction.java:146)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at com.mathworks.widgets.SyntaxTextPaneBase.processKeyEvent(SyntaxTextPaneBase.java:1189)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

Do you want me to open a new Issue?

**Comment by GavriYashar** [comment]
I've compiled 1.30 for Java 7, but my next guess is that there is no `java.lang.String.join` method, give me a minute.

**Comment by Nigsia** [comment]
Seems like that's the case: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-

**Comment by Nigsia** [comment]
Not working. https://github.com/GavriYashar/Matlab-Editor-Plugin/commit/1a73020fdfb1e9eb4134d00ab61ecb2923b73f52 did you forget to call the function? Because I can only see the implementation in here

**Comment by Nigsia** [comment]
Works perfect now :). 

Thank you very much.

**Comment by thengineer** [comment]
Okay, I've tried with v2018a and it works there!
The original post was made with v2016b (my preferred version)

This plug-in is really awesome, I must confess!

**Comment by thengineer** [comment]
okay, the J7 version seems to work for v2016b.

**Comment by PremKolar** [comment]
where is the MEP_1.30.jar please?! I can't find it.. :(

**Comment by PremKolar** [comment]
ok, some commands work, some don't.. when running my startup.m i get:

```
>> run('C:\work\matlabBOOT\startup.m')
Live Templates has been disabled for one or both following reasons:
  * No Replacement folder found in "C:\work\matlabBOOT\JARS
  * No Variables folder found in "C:\work\matlabBOOT\JARS\Replacements"
please set "path.mepr.rep" and "path.mepr.var" manually
Undefined variable "KeyStrokeUtil" or class "KeyStrokeUtil.getKeyStroke".
Error in startup (line 22)
ks_MyKeyReleaseFunction = KeyStrokeUtil.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, ~ctrl, ~shift, alt, false);
Error in run (line 96)
evalin('caller', [script ';']); 
```

**Comment by GavriYashar** [comment]
@PremKolar V1.30 is no longer supported. I've removed it from the release page.
also your `startup.m` should look like the example given: https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Setup#startupm-example

You may ignore the LiveTemplate warning if you don't need them. 
The error Thrown indicate that you didn't use `import at.mep.util.*;` line, but you don`t need that either, because this is just an example custom keyboard shortcut

**Comment by PremKolar** [comment]
ok everything works flawlessly now except the move line up/down commands..

I am forced to work on ML 2016b so the newest version of your code does not work..
could you let me use the 1.30 version, even though it is ~supprted anymore?? 
i would be so grateful.. i have to work with ML 40hours per week..

much thanks,
Niko

**Comment by GavriYashar** [comment]
oh dear R2016b... I don't have access to this version anymore... but let me think of something

**Comment by PremKolar** [comment]
my matlab programming skills are pretty solid.

but i cant compile java on this computer..

how do i proceed? 
i can write custom shortcuts for matlab (in matlab)? how do i do that?

thanks for your help!

**Comment by GavriYashar** [comment]
I'm writing an example page on how to create a custom shortcut. In the post above i linked two lines that are key to get this done. You'l need the `at.mep.editor.EditorWrapper` class and basically copy these two functions into matlab. an primitive example is found here:  https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Setup#creating-custom-key-press-callbacks-in-editor-optional

I'll write something... but i don't have access to matlab for the next three weeks.  I hope it doesn't take longer than like 30 to 60 minutes... YOu might want to check out this wiki article i'm currently editing: https://github.com/GavriYashar/Matlab-Editor-Plugin/wiki/Create-a-Custom-KeyRelease-Function-Example

**Comment by PremKolar** [comment]
wow! thank you so much for the effort!

the problem now is that my MEP version (1.25) does (at least) not know the getCurrentLinesStartEnd() method.. and i cant compile java here..

but you know what, i think i'll just wait until my employer decides to upgrade Matlab to the latest version and then use your latest release.. until then i will be ok without moving lines up and down :)

thanks,
Niko
