### ISSUE TITLE
MATLAB:Java:GenericException Java exception occurred: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by MzunguWaNjombe** [GavriYashar/Matlab-Editor-Plugin#147]
Hi,

first of all, thanks a lot for providing this awesome plugin!

Since a few days ago, I get the following error on starting MATLAB:

Initializing MEP: Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which
should be resolved as soon as possible.  Error detected was:
MATLAB:Java:GenericException
Java exception occurred:
java.lang.OutOfMemoryError: Java heap space
	at java.util.Properties.loadConvert(Properties.java:544)
	at java.util.Properties.load0(Properties.java:391)
	at java.util.Properties.load(Properties.java:341)
	at at.mep.prefs.Settings.load(Settings.java:203)
	at at.mep.prefs.Settings.load(Settings.java:193)
	at at.mep.prefs.Settings.loadSettings(Settings.java:62)
	at at.mep.prefs.Settings.getProperty(Settings.java:102)
	at at.mep.prefs.Settings.getPropertyBoolean(Settings.java:128)
	at at.mep.gui.AutoSwitcher.addCheckbox(AutoSwitcher.java:66)
	at at.mep.editor.EditorApp.setCallbacks(EditorApp.java:153)
	at at.mep.Start.setEditorCallbacks(Start.java:159)
	at at.mep.Start.start(Start.java:49) 

and MEP does not work.

I am using Kubuntu 18.04 and checked my update history for java-related packages, but could not find any. I also redownloaded MEP_1.34.jar and put it into the right directory, but this did not help. Do you have any further suggestions?

Best and thanks a lot,

Malte

**Comment by MzunguWaNjombe** [comment]
...Ok, after copying back an old startup.m, the issue magically disappeared.

**Comment by GavriYashar** [comment]
hi, 

Good to hear that the problem is solved. 
Might i ask what the difference is between those two startup files?

**Comment by MzunguWaNjombe** [comment]
Hi,
stupidly, I deleted the old one afterwards :-(. If this error occurs again, I will send it to you!
