### ISSUE TITLE
Editor Split View

### ISSUE THREAD

**Issue by GavriYashar** [GavriYashar/Matlab-Editor-Plugin#148]
![image](https://user-images.githubusercontent.com/1843623/53545835-11d03100-3b2b-11e9-9d70-b26d4101edea.png)

<details> <summary> Error Message </summary>

``` Matlab
Exception in thread "AWT-EventQueue-0": java.lang.NullPointerException
	at at.mep.editor.EditorApp.remKeyStrokes(EditorApp.java:317)
	at at.mep.editor.EditorApp.remKeyStrokes(EditorApp.java:313)
	at at.mep.editor.EditorApp.lambda$setCallbacks$0(EditorApp.java:209)
	at com.mathworks.mde.editor.MatlabEditor.fireEditorEvent(MatlabEditor.java:539)
	at com.mathworks.mde.editor.EditorViewClient$13.clientActivated(EditorViewClient.java:854)
	at com.mathworks.widgets.desk.DTClient.fireClientEvent(DTClient.java:1440)
	at com.mathworks.widgets.desk.DTClient.itemStateChanged(DTClient.java:1630)
	at com.mathworks.widgets.desk.DTInternalFrame.setSelected(DTInternalFrame.java:364)
	at com.mathworks.widgets.desk.DTClient.setSelected(DTClient.java:488)
	at com.mathworks.widgets.desk.DTOccupant.setSelected(DTOccupant.java:822)
	at com.mathworks.widgets.desk.DTSelectionManager.selectClient(DTSelectionManager.java:163)
	at com.mathworks.widgets.desk.DTMultipleClientFrame$LocalWindowListener$2.run(DTMultipleClientFrame.java:3367)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
</details>

**Comment by GavriYashar** [comment]
#134 duplicate
