### ISSUE TITLE
Still working with R2021b?

### ISSUE THREAD

**Issue by VictoriousRaptor** [GavriYashar/Matlab-Editor-Plugin#159]
**Describe the bug**
I've manually installed the plugin according to the guide. And it can display the message

> Initializing MEP: done

Then when I try to use some shortcuts, it bumps a lot of error.
    
**To Reproduce**
1. Start MATLAB
2. Do something

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Matlab Version R2021b x64

**error message**
<details><summary>Maybe in a different thread, but the same NullPointerException.</summary>

```Matlab
Initializing MEP: done
Exception in thread "AWT-EventQueue-0": java.lang.NullPointerException
	at at.mep.editor.EditorWrapper.getLongName(EditorWrapper.java:242)
	at at.mep.editor.EditorWrapper.getFile(EditorWrapper.java:261)
	at at.mep.editor.EditorWrapper.getFile(EditorWrapper.java:867)
	at at.mep.gui.AutoSwitcher.doYourThing(AutoSwitcher.java:37)
	at at.mep.gui.AutoSwitcher.lambda$addCheckbox$0(AutoSwitcher.java:79)
	at javax.swing.AbstractButton.fireStateChanged(AbstractButton.java:1916)
	at javax.swing.AbstractButton$Handler.stateChanged(AbstractButton.java:2340)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
	at javax.swing.DefaultButtonModel.setRollover(DefaultButtonModel.java:283)
	at javax.swing.plaf.basic.BasicButtonListener.mouseEntered(BasicButtonListener.java:261)
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4686)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4664)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4515)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

</details>

**Additional context**

**Comment by PremKolar** [comment]
i think it doesn't work anymore since Matlab decided to use the stupid LiveEditor also as the default editor. :(

**Comment by GavriYashar** [comment]
Hi there, I'm sorry for the late reply. 
I'm still on R2021a because in the newer releases (in my opinion) the editor, and the tab-completion is for my flavour to slow.
In addition I'm not really motivated to update the code of this Plugin, since Matlab is updating the editor and I'm not sure how long it'll work (+ the slow editor-thing).

I'm sorry for the inconvinience this plugin has caused.

Br

**Comment by PremKolar** [comment]
> Hi there, I'm sorry for the late reply. I'm still on R2021a because in the newer releases (in my opinion) the editor, and the tab-completion is for my flavour to slow. In addition I'm not really motivated to update the code of this Plugin, since Matlab is updating the editor and I'm not sure how long it'll work (+ the slow editor-thing).
> 
> I'm sorry for the inconvinience this plugin has caused.
> 
> What i could do is to upload my, unfinished even more rudimentary code that should work in newer releases.
> 
> Br

Hi Andreas,
I decided to downgrade to 2021a too so that I could use your plugin again. You were right, the old editor is much snappier esp. with tab completions! 
I just wanted to say thank you for the awesome plugin!!!! combined with trnkap's snippets extension, working with matlab in an oop style is actually fun :)
cheers,
niko

**Comment by OSHI7** [comment]
Hi Andreas,
Just a note of support--I am downgrading to use this add-on also!
Thank you for this incredible plug-in!!
Josh
