### ISSUE TITLE
Strg+F12 leads to the following error if I use methods with Access Lists

### ISSUE THREAD

**Issue by MartinLechner-TD** [GavriYashar/Matlab-Editor-Plugin#65]
If a class definition contains the following methods block the error message below is throw and the window contains no results.
```
methods(Access = {?classA})
    function doXYZ(obj, val1, val2)

    end
end

```

No method 'setAccess' with matching signature found for class 'at.justin.matlab.meta.MetaMethod'. 
matlabcontrol.MatlabInvocationException: Method did not return properly because of an internal MATLAB exception
	at matlabcontrol.MatlabInvocationException$Reason.asException(MatlabInvocationException.java:32)
	at matlabcontrol.JMIWrapper$MatlabThreadOperations.returningFeval(JMIWrapper.java:358)
	at matlabcontrol.JMIWrapper$MatlabThreadOperations.eval(JMIWrapper.java:308)
	at matlabcontrol.JMIWrapper$4.call(JMIWrapper.java:124)
	at matlabcontrol.JMIWrapper$4.call(JMIWrapper.java:121)
	at matlabcontrol.JMIWrapper$8.run(JMIWrapper.java:188)
	at com.mathworks.jmi.NativeMatlab.dispatchMTRequests(NativeMatlab.java:410)
Caused by: com.mathworks.jmi.MatlabException: No method 'setAccess' with matching signature found for class 'at.justin.matlab.meta.MetaMethod'.
	at com.mathworks.jmi.NativeMatlab.SendMatlabMessage(Native Method)
	at com.mathworks.jmi.NativeMatlab.sendMatlabMessage(NativeMatlab.java:259)
	at com.mathworks.jmi.MatlabLooper.sendMatlabMessage(MatlabLooper.java:120)
	at com.mathworks.jmi.Matlab.mtFevalConsoleOutput(Matlab.java:1780)
	at matlabcontrol.JMIWrapper$MatlabThreadOperations.returningFeval(JMIWrapper.java:329)
	... 5 more

**Error message without Access = ?classA**
No method 'setAccess' with matching signature found for class 'at.justin.matlab.meta.MetaMethod'. 
matlabcontrol.MatlabInvocationException: Method did not return properly because of an internal MATLAB exception
	at matlabcontrol.MatlabInvocationException$Reason.asException(MatlabInvocationException.java:32)
	at matlabcontrol.JMIWrapper$MatlabThreadOperations.returningFeval(JMIWrapper.java:358)
	at matlabcontrol.JMIWrapper$MatlabThreadOperations.eval(JMIWrapper.java:308)
	at matlabcontrol.JMIWrapper$4.call(JMIWrapper.java:124)
	at matlabcontrol.JMIWrapper$4.call(JMIWrapper.java:121)
	at matlabcontrol.JMIWrapper$8.run(JMIWrapper.java:188)
	at com.mathworks.jmi.NativeMatlab.dispatchMTRequests(NativeMatlab.java:410)
Caused by: com.mathworks.jmi.MatlabException: No method 'setAccess' with matching signature found for class 'at.justin.matlab.meta.MetaMethod'.
	at com.mathworks.jmi.NativeMatlab.SendMatlabMessage(Native Method)
	at com.mathworks.jmi.NativeMatlab.sendMatlabMessage(NativeMatlab.java:259)
	at com.mathworks.jmi.MatlabLooper.sendMatlabMessage(MatlabLooper.java:120)
	at com.mathworks.jmi.Matlab.mtFevalConsoleOutput(Matlab.java:1780)
	at matlabcontrol.JMIWrapper$MatlabThreadOperations.returningFeval(JMIWrapper.java:329)
	... 5 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at at.justin.matlab.gui.fileStructure.JTreeFilter.deepCopyNode(JTreeFilter.java:67)
	at at.justin.matlab.gui.fileStructure.JTreeFilter.filter(JTreeFilter.java:44)
	at at.justin.matlab.gui.fileStructure.JTreeFilter.filter(JTreeFilter.java:33)
	at at.justin.matlab.gui.fileStructure.FileStructure.findPattern(FileStructure.java:327)
	at at.justin.matlab.gui.fileStructure.FileStructure.access$200(FileStructure.java:32)
	at at.justin.matlab.gui.fileStructure.FileStructure$2.actionPerformed(FileStructure.java:60)
	at at.justin.matlab.gui.fileStructure.FileStructure$4.removeUpdate(FileStructure.java:191)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(Unknown Source)
	at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
	at javax.swing.text.AbstractDocument.remove(Unknown Source)
	at javax.swing.text.AbstractDocument.replace(Unknown Source)
	at javax.swing.text.JTextComponent.setText(Unknown Source)
	at at.justin.matlab.gui.fileStructure.FileStructure.showDialog(FileStructure.java:407)
	at at.justin.matlab.editor.MEPActionE.showFileStructure(MEPActionE.java:148)
	at at.justin.matlab.editor.MEPActionE.access$100(MEPActionE.java:20)
	at at.justin.matlab.editor.MEPActionE$3.actionPerformed(MEPActionE.java:41)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at com.mathworks.widgets.SyntaxTextPaneBase.processKeyEvent(SyntaxTextPaneBase.java:1189)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by GavriYashar** [comment]
access is not empty, did something wrong when testing
