### ISSUE TITLE
Too many Exceptions while running the plugin.

### ISSUE THREAD

**Issue by Esmaeili-Najafabadi** [GavriYashar/Matlab-Editor-Plugin#89]
At the start of Matlab the following errors are reported. Besides, while working most of the features, usually the Matlab generates too many of such errors. They are seen while changing between workspace and Matlab.

Live Templates has been disabled for one or both following reasons:
  * No Replacement folder found in "C:\Program Files\MATLAB\MEP
  * No Variables folder found in "C:\Program Files\MATLAB\MEP\Replacements"
please set "path.mepr.rep" and "path.mepr.var" manually
java.io.FileNotFoundException: <path>\CustomProps.properties (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at at.mep.prefs.Settings.load(Settings.java:142)
	at at.mep.prefs.Settings.loadSettings(Settings.java:41)
	at at.mep.Start.loadSettings(Start.java:105)
	at at.mep.Start.start(Start.java:21)
java.io.FileNotFoundException: <path>\DefaultProps.properties (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at at.mep.prefs.Settings.load(Settings.java:142)
	at at.mep.prefs.Settings.loadSettings(Settings.java:42)
	at at.mep.Start.loadSettings(Start.java:105)
	at at.mep.Start.start(Start.java:21)
java.io.FileNotFoundException: <path>\CustomProps.properties (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at at.mep.prefs.Settings.store(Settings.java:61)
	at at.mep.Start.start(Start.java:42)
java.io.FileNotFoundException: <path>\CustomProps.properties (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at at.mep.prefs.Settings.load(Settings.java:142)
	at at.mep.prefs.Settings.loadSettings(Settings.java:41)
	at at.mep.prefs.Settings.getProperty(Settings.java:75)
	at at.mep.prefs.Settings.getPropertyColor(Settings.java:125)
	at at.mep.editor.EditorApp.setCallbacks(EditorApp.java:193)
	at at.mep.editor.EditorApp.addMatlabCallback(EditorApp.java:58)
java.io.FileNotFoundException: <path>\DefaultProps.properties (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at at.mep.prefs.Settings.load(Settings.java:142)
	at at.mep.prefs.Settings.loadSettings(Settings.java:42)
	at at.mep.prefs.Settings.getProperty(Settings.java:75)
	at at.mep.prefs.Settings.getPropertyColor(Settings.java:125)
	at at.mep.editor.EditorApp.setCallbacks(EditorApp.java:193)
	at at.mep.editor.EditorApp.addMatlabCallback(EditorApp.java:58)

**Comment by GavriYashar** [comment]
the setting for live templates (`feature.enableReplacements`) should be `false` on default. It is not setup correctly unless you've followed the setup for live templates
`CustomProps.properties` and `DefaultProps.properties` must be valid, otherwise MEP can't even start.

**Comment by GavriYashar** [comment]
also instead of throwing errors i could use default values instead, and check on the startup if all values are correct
